# Generated by Django 3.2.2 on 2021-05-14 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imovel', models.CharField(max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=50)),
                ('localizacao', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='valor',
        ),
        migrations.AlterField(
            model_name='venda',
            name='imovel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.imovel', verbose_name='Imóvel'),
        ),
    ]
