# Generated by Django 3.2.2 on 2021-05-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_auto_20210514_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='pagamento',
            field=models.CharField(choices=[('A', 'À Vista'), ('P', '180 Parcelas')], max_length=1, null=True),
        ),
    ]
