# Generated by Django 3.2.2 on 2021-05-14 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venda', '0003_alter_venda_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='imovel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Imóvel'),
        ),
    ]
