# Generated by Django 3.2.2 on 2021-05-14 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venda', '0004_alter_venda_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='corretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Corretor'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='imovel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.imovel', verbose_name='Imóvel'),
        ),
    ]
