# Generated by Django 3.2.2 on 2021-05-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0005_auto_20210514_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='corretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.corretor', verbose_name='Corretor'),
        ),
    ]
