# Generated by Django 3.2.2 on 2021-05-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0007_alter_venda_corretor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='pagamento',
            field=models.CharField(choices=[('À Vista', 'À Vista'), ('180 Parcelas', '180 Parcelas')], max_length=30, null=True),
        ),
    ]
