# Generated by Django 3.2.2 on 2021-05-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20210512_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='client_pics'),
        ),
    ]
